issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude:
      - SA1019

run:
  deadline: 5m
  skip-files:
      - nsxt/resource_nsxt_rest_dependants.go

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goheader
    - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - predeclared
    - revive
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - vet
    - vetshadow
    - whitespace

linters-settings:
  errcheck:
    ignore: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set,fmt:.*,io:Close
  gofmt:
    simplify: false
