# name: Codecov

# on:
#   pull_request:
#   push:
#     branches:
#       - main

# jobs:
#   codecov:
#     runs-on: ubuntu-latest
    
#     env:
#       TF_ACC: "1"
#       NSXT_MANAGER_HOST: "10.215.102.137"
#       NSXT_USERNAME: "admin"
#       NSXT_PASSWORD: "d5*Hn+-ZNgXS"
#       NSXT_ORG: "default"
#       NSXT_PROJECT: "Dev_project"
#       NSXT_VPC: "dev_vpc"
#       NSXT_PROJECT_INFRA_TEST_GROUP_NAME: "ORG-default-PROJECT-Dev_project-VPC-dev_vpc-default"
#       NSXT_PROJECT_INFRA_TEST_IP_ADDRESS_BLOCK_NAME: "ip_block_dev"
#       NSXT_PROJECT_INFRA_TEST_IP_ADDRESS_POOL_NAME: "_VPC_IP_ADDRESS_POOL--dev_vpc"
#       NSXT_PROJECT_INFRA_TEST_CONTEXT_PROFILE_NAME: "360ANTIV"
#       NSXT_PROJECT_INFRA_TEST_SERVICE_ID: "Active_Directory_Server"
#       NSXT_INFRA_TEST_GROUP_NAME: "ServiceInsertion_NSGroup"
#       NSXT_INFRA_TEST_IP_ADDRESS_BLOCK_NAME: "ip_block_test"
#       NSXT_INFRA_TEST_IP_ADDRESS_POOL_NAME: "test-ip-pool"
#       NSXT_INFRA_TEST_CONTEXT_PROFILE_ID: "360ANTIV"
#       NSXT_INFRA_TEST_SERVICE_ID: "Active_Directory_Server"
#       NSXT_TEST_VM_ID: "bd0a80fd-f25a-4cdd-8727-3a22220d00e9"
#       NSXT_TEST_VM_EXTERNAL_ID: "bd0a80fd-f25a-4cdd-8727-3a22220d00e9"
#       NSXT_TEST_VM_POWER_STATE: "VM_RUNNING"

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install Terraform
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: 1.4.2
#           terraform_wrapper: false

#       - name: Install Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.18.4

#       - name: Install dependencies
#         run: |
#           go get -v ./...

#       - name: Run tests and generate coverage report
#         run: |
#           TF_ACC=1 TF_LOG=TRACE go test -v -coverprofile=coverage_report.json ./nsxt/
#           go tool cover -html=coverage_report.json -o coverage_report.html

#       - name: Upload coverage reports to Codecov
#         uses: codecov/codecov-action@v3
#         with:
#           token: ${{ secrets.CODECOV_TOKEN }}
